"""
Generate docs/DATA_DICTIONARY.md directly from the source schema and the frozen
extract, so the dictionary cannot drift from the data it describes.

Usage:  python src/make_data_dictionary.py
"""

from __future__ import annotations

import gzip
import json
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw" / "nyc311_pothole_cy2024.json.gz"
SCHEMA = ROOT / "data" / "raw" / "source_schema.json"
OUT = ROOT / "docs" / "DATA_DICTIONARY.md"

# Availability classification, kept in sync with the leakage audit in the notebook.
POST_OUTCOME = {
    "closed_date": "**POST-OUTCOME** — arithmetic target; using it as a feature leaks",
    "resolution_description": "**POST-OUTCOME** — defines the label; using it as a feature leaks",
    "resolution_action_updated_date": "**POST-OUTCOME** — last back-office write",
    "status": "**POST-OUTCOME** — the disposition itself",
}

MANUAL_NOTES = {
    "unique_key": "Primary key of the cohort. Verified unique (0 duplicates).",
    "created_date": "Cohort filter field. Parsed as ISO-8601 **with milliseconds**; a naive "
                    "`format=\"%Y-%m-%dT%H:%M:%S\"` silently coerces every row to NaN.",
    "closed_date": "Null ⟺ request not closed (right-censored). 13 records have `closed_date < created_date`.",
    "resolution_description": "13 distinct strings; mapped to 8 semantic classes in §9.1 of the notebook. "
                              "This column **is** the outcome definition.",
    "status": "Only 2 values. `Closed` is NOT equivalent to `repaired` — see §9.1.",
    "incident_address": "**Street-level, not point-level** — no house number. `\"BROADWAY\"` occurs 211× "
                        "in this cohort, so it cannot identify a defect.",
    "incident_zip": "2.21% null. 205 distinct values (includes non-NYC-adjacent codes).",
    "location": "**Nested GeoJSON object**, not a scalar. Breaks `nunique()`, `groupby()`, and any "
                "blanket column sweep. Must be flattened or excluded.",
    "agency": "Constant `DOT` **because of the cohort filter** — zero variance, no information.",
    "complaint_type": "Constant `Street Condition` by construction — zero variance.",
    "descriptor": "Constant `Pothole` by construction — zero variance.",
    "open_data_channel_type": "Constant `UNKNOWN` for 100% of rows — **no information at all**, and "
                              "it is the field you would need to study how requests are submitted.",
    "latitude": "52.52% coverage. Published as a number but arrives as a string for present rows.",
    "longitude": "52.52% coverage. Same string-typing quirk as `latitude`.",
    "community_board": "100% non-null (administrative geocode always succeeds) but is **not** a "
                       "street-level locator; 76 distinct values.",
    "borough": "Includes `Unspecified` (125 rows) — excluded from borough comparisons.",
}


def strip_html(s: str) -> str:
    s = re.sub(r"<[^>]+>", "", s or "")
    return re.sub(r"\s+", " ", s).strip()


def main() -> int:
    schema = json.loads(SCHEMA.read_text())
    src = {c["fieldName"]: c for c in schema["columns"]}
    df = pd.DataFrame(json.loads(gzip.decompress(RAW.read_bytes())))

    union = {c for c in df.columns}
    present = [c for c in df.columns if c not in ("created_dt", "closed_dt", "elapsed_h")]
    absent = sorted(set(src) - union)

    lines: list[str] = []
    A = lines.append

    A("# Data Dictionary")
    A("")
    A("Generated by `src/make_data_dictionary.py` directly from the frozen extract and the")
    A("publisher's schema snapshot, so it cannot drift from the data.")
    A("")
    A(f"* **Extract:** `data/raw/nyc311_pothole_cy2024.json.gz`")
    A(f"* **SHA-256:** `{json.loads((ROOT/'data/raw/source_metadata.json').read_text())['extract_sha256_uncompressed']}`")
    A(f"* **Rows:** {len(df):,}  ·  **Columns present in extract:** {len(present)}")
    A(f"* **Columns declared upstream but absent here:** {len(absent)} (null for every record of this cohort)")
    A("")
    A("## How to read the `available_at` column")
    A("")
    A("`intake` — the value exists at the moment the report is filed, so it is admissible for a")
    A("forward-looking claim. `POST-OUTCOME` — the value is written *after* the outcome is known.")
    A("Using any `POST-OUTCOME` column as a model feature leaks the answer (§8 of the notebook).")
    A("")
    A("## Columns present in the extract")
    A("")
    A("| # | column | declared type | observed dtype | available_at | non-null | % null | distinct | example |")
    A("|---|---|---|---|---|---|---|---|---|")
    for i, c in enumerate(present, 1):
        s = df[c]
        nested = any(isinstance(v, (dict, list)) for v in s.head(500))
        obs = "object (nested)" if nested else str(s.dtype)
        avail = "POST-OUTCOME" if c in POST_OUTCOME else "intake"
        nd = "—" if nested else f"{int(s.nunique(dropna=True)):,}"
        ex = "" if s.dropna().empty else str(s.dropna().iloc[0]).replace("|", "\\|")[:38]
        A(f"| {i} | `{c}` | {src[c].get('dataTypeName','')} | {obs} | {avail} | "
          f"{int(s.notna().sum()):,} | {100*s.isna().mean():.2f}% | {nd} | `{ex}` |")
    A("")
    A("## Declared upstream, absent from this extract")
    A("")
    A("Socrata omits null fields per record; these are null for every one of the "
      f"{len(df):,} pothole records.")
    A("")
    A("| column | declared type |")
    A("|---|---|")
    for c in absent:
        A(f"| `{c}` | {src[c].get('dataTypeName','')} |")
    A("")
    A("## Column notes, caveats and traps")
    A("")
    for c in present:
        note = MANUAL_NOTES.get(c) or POST_OUTCOME.get(c)
        if not note:
            continue
        desc = strip_html(src.get(c, {}).get("description", ""))
        A(f"### `{c}`")
        A("")
        if desc:
            A(f"*Publisher description:* {desc}")
        A(f"*Analyst note:* {note}")
        A("")
    A("## Derived columns created by the notebook")
    A("")
    A("| column | definition |")
    A("|---|---|")
    A("| `created_dt`, `closed_dt` | timestamps parsed with `format=\"ISO8601\"`, tz stripped to naive |")
    A("| `elapsed_h` | `(closed_dt - created_dt)` in **calendar** hours; null when not closed |")
    A("| `outcome_class` | `resolution_description` mapped to 8 semantic classes (§9.1) |")
    A("| `n_reports_at_addr` | count of reports sharing a street-level `incident_address` (§10.2) |")
    A("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size:,} bytes, "
          f"{len(present)} columns documented, {len(absent)} absent columns listed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
